apiVersion: v1
kind: Service
metadata:
  name: nodejs-cicd-demo-service
spec:
  type: NodePort
  selector:
    app: nodejs-cicd-demo
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
